<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EfetivosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //criar efetivos
        DB::table('efetivos')->insert([
            [
                'nome' => 'Davis Ferreira de Lima',
                'rg' => '28922',
                'nome_guerra' => 'Davis',
                'trigrama' => 'DVS',
                'precedencia_id' => 12,
                'quadro_id' => 2,
                'especialidade_id' => 13,
                'subunidade_id' => 1,
                'secao_id' => 2,
                'funcao_id' => 2,
                'status_id' => 1,
                'data_nascimento' => '1981-03-09',
                'user_id' => 1,
                'foto' => null,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'nome' => 'Fulano de Tal',
                'rg' => '31001',
                'nome_guerra' => 'Tal',
                'trigrama' => 'TAL',
                'precedencia_id' => 1,
                'quadro_id' => 1,
                'especialidade_id' => 1,
                'subunidade_id' => 1,
                'secao_id' => 1,
                'funcao_id' => 1,
                'status_id' => 1,
                'data_nascimento' => '1990-02-02',
                'user_id' => 2,
                'foto' => null,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'nome' => 'Ciclano de Brau',
                'rg' => '32002',
                'nome_guerra' => 'Brau',
                'trigrama' => 'CIC',
                'precedencia_id' => 1,
                'quadro_id' => 1,
                'especialidade_id' => 1,
                'subunidade_id' => 1,
                'secao_id' => 1,
                'funcao_id' => 1,
                'status_id' => 1,
                'data_nascimento' => '1990-03-03',
                'user_id' => 3,
                'foto' => null,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'nome' => 'João Steward',
                'rg' => '33003',
                'nome_guerra' => 'J Steward',
                'trigrama' => 'JST',
                'precedencia_id' => 1,
                'quadro_id' => 1,
                'especialidade_id' => 1,
                'subunidade_id' => 1,
                'secao_id' => 1,
                'funcao_id' => 1,
                'status_id' => 1,
                'data_nascimento' => '1990-04-04',
                'user_id' => 4,
                'foto' => null,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'nome' => 'Pedro Rhodes',
                'rg' => '34004',
                'nome_guerra' => 'P Rhodes',
                'trigrama' => 'PRO',
                'precedencia_id' => 1,
                'quadro_id' => 1,
                'especialidade_id' => 1,
                'subunidade_id' => 1,
                'secao_id' => 1,
                'funcao_id' => 1,
                'status_id' => 1,
                'data_nascimento' => '1990-05-05',
                'user_id' => 5,
                'foto' => null,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'nome' => 'José Seichs',
                'rg' => '35005',
                'nome_guerra' => 'Seichs',
                'trigrama' => 'SEI',
                'precedencia_id' => 1,
                'quadro_id' => 1,
                'especialidade_id' => 1,
                'subunidade_id' => 1,
                'secao_id' => 1,
                'funcao_id' => 1,
                'status_id' => 1,
                'data_nascimento' => '1990-06-06',
                'user_id' => 6,
                'foto' => null,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'nome' => 'Maria Margot',
                'rg' => '36006',
                'nome_guerra' => 'Maria',
                'trigrama' => 'MAR',
                'precedencia_id' => 1,
                'quadro_id' => 1,
                'especialidade_id' => 1,
                'subunidade_id' => 1,
                'secao_id' => 1,
                'funcao_id' => 1,
                'status_id' => 1,
                'data_nascimento' => '1990-07-07',
                'user_id' => 7,
                'foto' => null,
                'created_at' => now(),
                'updated_at' => null,
            ],
            [
                'nome' => 'Joaquina Gall',
                'rg' => '37007',
                'nome_guerra' => 'Joaquina',
                'trigrama' => 'GAL',
                'precedencia_id' => 1,
                'quadro_id' => 1,
                'especialidade_id' => 1,
                'subunidade_id' => 1,
                'secao_id' => 1,
                'funcao_id' => 1,
                'status_id' => 1,
                'data_nascimento' => '1990-08-08',
                'user_id' => 8,
                'foto' => null,
                'created_at' => now(),
                'updated_at' => null,
            ],
        ]);
    }
}
